spring:
  application:
    name: hhp7_concert_reservation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    properties:
#      hibernate:
#        jdbc:
#          batch_size: 60
#        order_inserts: true
#        rewriteBatchedStatements: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com:
      hhp7:
        concertreservation:
            repository: warn
            service: warn
            controller: warn

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs       # 기본값: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI 접속 경로 (기본값: /swagger-ui.html)